### ISSUE TITLE
Fatal error: args are formatted badly

### ISSUE THREAD

**Issue by ChrisHoffmann96** [sroddy/flutter_string_encryption#12]
Thanks for the Plugin! The Android Part works for me, but ios crashes. In Android Studio, i don't get an error-message, it just stops. In XCode:

In the SwiftFlutterStringEncryptionPlugin, line 58:

case "generate_key_from_password":
      guard let args = call.arguments as? [String: String] else {
        fatalError("args are formatted badly")
      }

this error gets thrown. I did't change anything there, it just always throws this error. Any help would be appreciated, as this lib is great.

I dont have any more information, there is no more error log or anything: 
https://ibb.co/dW8DuU

**Comment by sroddy** [comment]
Looks like the platform side is receiving data in a bad format. Perhaps Flutter has changed something in latest releases. Can you please paste the output of:
flutter doctor -v

I’ll try to take a look later today or tomorrow

**Comment by ChrisHoffmann96** [comment]
Thanks for the quick answer! 

doctor -v output:

[✓] Flutter (Channel beta, v0.8.2, on Mac OS X 10.14 18A391, locale de-DE)
    • Flutter version 0.8.2 at /Users/apple/Desktop/flutter
    • Framework revision 5ab9e70727 (5 weeks ago), 2018-09-07 12:33:05 -0700
    • Engine revision 58a1894a1c
    • Dart version 2.1.0-dev.3.1.flutter-760a9690c2

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/apple/Library/Android/sdk
    • Android NDK at /Users/apple/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 29.0.2
    • Dart plugin version 181.5616
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[!] Connected devices
    ! No devices available

! Doctor found issues in 1 category.

**Comment by gramueller** [comment]
I'm getting the same Error Stack. Is there already a fix out there? I'm pretty desperate right now.

**Comment by calimbadevs** [comment]
Any updates on the fix for this? Need to know wheter i have to search for another encryption library or not. Would like to keep using this because its great but if the project wont be updated anymore ill have to search.

**Comment by sroddy** [comment]
I've tested it with recents versions of Flutter and I'm not able to reproduce. Can you please provide a password/salt combination (something that you are not actually using) that triggers this error?
Thanks

**Comment by ChrisHoffmann96** [comment]
Oh im sorry, i didnt even answer and close this. 
There was another mistake somewhere else but neither xcode nor the flutter logs were able to show that to me. The secure storage gave me a null value (which it shouldnt) and which was give your plugin as the salt. So that was the problem after all, there was no problem with your plugin.

Sorry for the inconvenience! And keep up the good work.
