### ISSUE TITLE
remove flutter dependency

### ISSUE THREAD

**Issue by mathieujobin** [sroddy/flutter_string_encryption#8]
Since this is a string encryption plugin, it would be nice to remove the UI dependency on it.

I do intend to use it with flutter, but I wanted to test things out in a simple dart program. unfortunately, I can't

```
$ dart teststrenc.dart 
The built-in library 'dart:ui' is not available on the stand-alone VM.
'package:flutter/src/services/binding.dart': error: line 6 pos 1: library handler failed
import 'dart:ui' as ui;
^
```

**Comment by sroddy** [comment]
The plugin itself does not depend on the ui, but it depends on Method Channels which are bundled inside Flutter.
I don't think there is an easy way to easily get rid of that dependency, however you should be able to test your logic using flutter tests and a mock implementation of the `StringCryptor` protocol

**Comment by mathieujobin** [comment]
thanks
